using System.Collections.Immutable;
using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace NetWebAssemblyTSTypeGenerator.Tests
{
    public class GeneratorTest : IDisposable
    {
        private readonly List<string> _emitTempDir;
        private const string TestAssemblyName = "testassembly";

        public GeneratorTest()
        {
            _emitTempDir = new List<string>();
        }

        public void Dispose()
        {
            foreach (var d in _emitTempDir)
            {
                try
                {
                    var di = new DirectoryInfo(d);
                    foreach (var fi in di.GetFiles())
                    {
                        fi.Delete();
                    }
                    di.Delete();
                }
                catch (Exception)
                {
                    //
                }
            }

            GC.SuppressFinalize(this);
        }

        private static string GetTempDirectory()
        {
            var tempDirPath = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
            Directory.CreateDirectory(tempDirPath);
            return tempDirPath;
        }

        [Fact]
        public void BaseGeneratorTest()
        {
            var outputDir = GetTempDirectory();
            _emitTempDir.Add(outputDir);

            var input = CreateCompilation(@"
using System;
using System.Runtime.InteropServices.JavaScript;

return 0;

namespace MyCode
{
    public partial class MyClass
    {
        [JSExport]
        internal static string Hello()
        {
            return ""Hello"";
        }

        [JSImport(""my.awesome.module"", ""main.mjs"")]
        internal static partial string FooBar();
    }
}
");

            GeneratorDriver driver = CSharpGeneratorDriver.Create(
                new[] { new NetWebAssemblyTSTypeGenerator() },
                optionsProvider: new CustomAnalyzerConfigOptionsProvider(
                    new CustomAnalyzerConfigOptions(
                        new Dictionary<string, string>{
                            { Constants.BuildPropertyJSPortOverrideTypeDefinitionOutputDir, outputDir},
                            { "build_property.AssemblyName", TestAssemblyName }
                        }.ToImmutableDictionary()
                    )
                )
            );

            driver.RunGeneratorsAndUpdateCompilation(input, out var _ /* outputCompilation */, out var diagnostics);

            Assert.True(diagnostics.IsEmpty, string.Join(',', diagnostics.Select(v => v.GetMessage())));
            // NOTE: Cannot use JSImport, JSExport attribute because it could not reference assemblies...
            // so outputCompilation.GetDiagnostics().IsEmpty will false

            var outputFileName = Path.Combine(outputDir, $"index.d.ts");
            Assert.True(File.Exists(outputFileName));

            var outputFileContent = File.ReadAllText(outputFileName);
            Assert.Contains(@$"/** Generated: for {TestAssemblyName}.dll */", outputFileContent);
            Assert.Contains(@$"export const getTypedAssemblyExports: (originalGetAssemblyExports: Promise<any>)", outputFileContent);
            var exportedJsonContent = string.Join("\n",
                outputFileContent.Split('\n')
                    .SkipWhile(v => v != "/* AutoGeneratedExportsHelperStart */")
                    .Skip(1)
                    .TakeWhile(v => v != "/* AutoGeneratedExportsHelperEnd */")).Trim();

            Assert.True(exportedJsonContent == @"{
  ""MyCode"": {
    ""MyClass"": {
      ""Hello"": () => any /* TODO */
    }
  }
}", exportedJsonContent);

            Assert.Contains(@$"export const setTypedModuleImports: <T extends ImportModuleNames>", outputFileContent);
            Assert.Contains("type ImportModuleNames = 'main.mjs'", outputFileContent);
            Assert.Contains("type ImportModuleValues<T extends ImportModuleNames>", outputFileContent);
            Assert.Contains("T extends 'main.mjs'", outputFileContent);
            Assert.Contains(@"{
  ""my"": {
    ""awesome"": {
      ""module"": () => any /* TODO */
    }
  }
}", outputFileContent);
        }

        [Fact]
        public void MultipleFilesWithoutJSAttributesInProgramCs()
        {
            var outputDir = GetTempDirectory();
            _emitTempDir.Add(outputDir);

            // Program.cs: top-level statements with NO JSExport/JSImport
            var programSource = @"
using System;
using System.Runtime.InteropServices.JavaScript;

return 0;
";

            // Another file: contains JSExport/JSImport
            var myClassSource = @"
using System;
using System.Runtime.InteropServices.JavaScript;

namespace MyCode
{
    public partial class MyClass
    {
        [JSExport]
        internal static string Hello()
        {
            return ""Hello"";
        }

        [JSImport(""my.awesome.module"", ""main.mjs"")]
        internal static partial string FooBar();
    }
}
";

            var input = CreateCompilationFromSources(programSource, myClassSource);

            GeneratorDriver driver = CSharpGeneratorDriver.Create(
                new[] { new NetWebAssemblyTSTypeGenerator() },
                optionsProvider: new CustomAnalyzerConfigOptionsProvider(
                    new CustomAnalyzerConfigOptions(
                        new Dictionary<string, string>{
                            { Constants.BuildPropertyJSPortOverrideTypeDefinitionOutputDir, outputDir},
                            { "build_property.AssemblyName", TestAssemblyName }
                        }.ToImmutableDictionary()
                    )
                )
            );

            driver.RunGeneratorsAndUpdateCompilation(input, out var _, out var diagnostics);

            Assert.True(diagnostics.IsEmpty, string.Join(',', diagnostics.Select(v => v.GetMessage())));

            var outputFileName = Path.Combine(outputDir, $"index.d.ts");
            Assert.True(File.Exists(outputFileName));

            var outputFileContent = File.ReadAllText(outputFileName);
            Assert.Contains(@$"/** Generated: for {TestAssemblyName}.dll */", outputFileContent);

            var exportedJsonContent = string.Join("\n",
                outputFileContent.Split('\n')
                    .SkipWhile(v => v != "/* AutoGeneratedExportsHelperStart */")
                    .Skip(1)
                    .TakeWhile(v => v != "/* AutoGeneratedExportsHelperEnd */")).Trim();

            Assert.True(exportedJsonContent == @"{
  ""MyCode"": {
    ""MyClass"": {
      ""Hello"": () => any /* TODO */
    }
  }
}", exportedJsonContent);

            Assert.Contains("type ImportModuleNames = 'main.mjs'", outputFileContent);
        }

        [Fact]
        public void FileScopedNamespaceTest()
        {
            var outputDir = GetTempDirectory();
            _emitTempDir.Add(outputDir);

            // Program.cs: top-level statements with NO JSExport/JSImport
            var programSource = @"
using System;
using System.Runtime.InteropServices.JavaScript;

return 0;
";

            // Another file with FILE-SCOPED NAMESPACE (modern C# style)
            var myClassSource = @"
using System;
using System.Runtime.InteropServices.JavaScript;

namespace MyCode;

public partial class MyClass
{
    [JSExport]
    internal static string Hello()
    {
        return ""Hello"";
    }

    [JSImport(""my.awesome.module"", ""main.mjs"")]
    internal static partial string FooBar();
}
";

            var input = CreateCompilationFromSources(programSource, myClassSource);

            GeneratorDriver driver = CSharpGeneratorDriver.Create(
                new[] { new NetWebAssemblyTSTypeGenerator() },
                optionsProvider: new CustomAnalyzerConfigOptionsProvider(
                    new CustomAnalyzerConfigOptions(
                        new Dictionary<string, string>{
                            { Constants.BuildPropertyJSPortOverrideTypeDefinitionOutputDir, outputDir},
                            { "build_property.AssemblyName", TestAssemblyName }
                        }.ToImmutableDictionary()
                    )
                )
            );

            driver.RunGeneratorsAndUpdateCompilation(input, out var _, out var diagnostics);

            Assert.True(diagnostics.IsEmpty, string.Join(',', diagnostics.Select(v => v.GetMessage())));

            var outputFileName = Path.Combine(outputDir, $"index.d.ts");
            Assert.True(File.Exists(outputFileName));

            var outputFileContent = File.ReadAllText(outputFileName);

            var exportedJsonContent = string.Join("\n",
                outputFileContent.Split('\n')
                    .SkipWhile(v => v != "/* AutoGeneratedExportsHelperStart */")
                    .Skip(1)
                    .TakeWhile(v => v != "/* AutoGeneratedExportsHelperEnd */")).Trim();

            // With file-scoped namespace, the namespace should be correctly detected
            Assert.True(exportedJsonContent == @"{
  ""MyCode"": {
    ""MyClass"": {
      ""Hello"": () => any /* TODO */
    }
  }
}", exportedJsonContent);
        }

        [Fact]
        public void MultipleFilesWithJSInteropGeneratedIntermediateFile()
        {
            var outputDir = GetTempDirectory();
            _emitTempDir.Add(outputDir);

            // Program.cs: top-level statements with NO JSExport/JSImport
            var programSource = @"
using System;
using System.Runtime.InteropServices.JavaScript;

return 0;
";

            // The user's class file with JSExport/JSImport
            var myClassSource = @"
using System;
using System.Runtime.InteropServices.JavaScript;

namespace MyCode
{
    public partial class MyClass
    {
        [JSExport]
        internal static string Hello()
        {
            return ""Hello"";
        }

        [JSImport(""my.awesome.module"", ""main.mjs"")]
        internal static partial string FooBar();
    }
}
";

            // Simulate what the JSInterop SourceGenerator generates for MyClass:
            // It generates a partial class with the implementation/registration
            // but WITHOUT [JSExport]/[JSImport] attributes
            var jsInteropGeneratedSource = @"
// <auto-generated/>
namespace MyCode
{
    partial class MyClass
    {
        private static System.Runtime.InteropServices.JavaScript.JSFunctionBinding __signature_s_Hello1;

        [System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void __Register_s_Hello_1()
        {
        }

        internal static partial string FooBar()
        {
            return null;
        }
    }
}
";

            var input = CreateCompilationFromSources(programSource, myClassSource, jsInteropGeneratedSource);

            GeneratorDriver driver = CSharpGeneratorDriver.Create(
                new[] { new NetWebAssemblyTSTypeGenerator() },
                optionsProvider: new CustomAnalyzerConfigOptionsProvider(
                    new CustomAnalyzerConfigOptions(
                        new Dictionary<string, string>{
                            { Constants.BuildPropertyJSPortOverrideTypeDefinitionOutputDir, outputDir},
                            { "build_property.AssemblyName", TestAssemblyName }
                        }.ToImmutableDictionary()
                    )
                )
            );

            driver.RunGeneratorsAndUpdateCompilation(input, out var _, out var diagnostics);

            Assert.True(diagnostics.IsEmpty, string.Join(',', diagnostics.Select(v => v.GetMessage())));

            var outputFileName = Path.Combine(outputDir, $"index.d.ts");
            Assert.True(File.Exists(outputFileName));

            var outputFileContent = File.ReadAllText(outputFileName);

            var exportedJsonContent = string.Join("\n",
                outputFileContent.Split('\n')
                    .SkipWhile(v => v != "/* AutoGeneratedExportsHelperStart */")
                    .Skip(1)
                    .TakeWhile(v => v != "/* AutoGeneratedExportsHelperEnd */")).Trim();

            Assert.True(exportedJsonContent == @"{
  ""MyCode"": {
    ""MyClass"": {
      ""Hello"": () => any /* TODO */
    }
  }
}", exportedJsonContent);
        }

        // FIXME: TargetArchitecture, TargetOS, RuntimeIdentifier...how to use wasm-tools???
        private static Compilation CreateCompilation(string source)
            => CSharpCompilation.Create("compilation",
                new[] { CSharpSyntaxTree.ParseText(source) },
                new[] { MetadataReference.CreateFromFile(typeof(Binder).GetTypeInfo().Assembly.Location) },
                new CSharpCompilationOptions(OutputKind.ConsoleApplication));

        private static Compilation CreateCompilationFromSources(params string[] sources)
            => CSharpCompilation.Create("compilation",
                sources.Select(s => CSharpSyntaxTree.ParseText(s)).ToArray(),
                new[] { MetadataReference.CreateFromFile(typeof(Binder).GetTypeInfo().Assembly.Location) },
                new CSharpCompilationOptions(OutputKind.ConsoleApplication));
    }
}

