<Project Sdk="Microsoft.NET.Sdk">
  <!-- ref: https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md -->
  <PropertyGroup>
    <Title>NetWebAssemblyTSTypeGenerator</Title>
    <Description>NetWebAssemblyTSTypeGenerator is Generator for typing .NET JavaScript interop on WebAssembly.</Description>
    <Authors>YusukeYamada</Authors>
    <PackageProjectUrl>https://github.com/yamachu/NetWebAssemblyTSTypeGenerator</PackageProjectUrl>
    <RepositoryUrl>https://github.com/yamachu/NetWebAssemblyTSTypeGenerator</RepositoryUrl>
    <Copyright>Copyright © YusukeYamada 2022</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageVersion>$(Version)</PackageVersion>

    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>11</LangVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild> <!-- Generates a package at build -->
    <IncludeBuildOutput>false</IncludeBuildOutput> <!-- Do not include the generator as a lib dependency -->
    <NoWarn>RS1036;RS1042</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" PrivateAssets="all" />
    <PackageReference Include="System.Text.Json" Version="8.0.6" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <!-- Package the generator in the analyzer directory of the nuget package -->
    <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    <None Include="../README.md" Pack="true" PackagePath="\" />
    <None Include="../LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
