name: Release packages
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
  id-token: write  # enable GitHub OIDC token issuance for this job

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Validate release version
        id: validate
        run: |
          VERSION="${{ github.ref_name }}"
          cd src; PACKAGE_VERSION=$(dotnet msbuild -getProperty:PackageVersion)
          if [ "$VERSION" != "$PACKAGE_VERSION" ]; then
              echo "❌ タグ名 $VERSION とプロジェクトの PackageVersion $PACKAGE_VERSION が一致しません"
              exit 1
          fi
      - name: Delete tag on validation failure
        if: failure()
        run: |
          VERSION="${{ github.ref_name }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git push --delete origin "$VERSION"
          echo "❌ バージョン検証に失敗したため、タグ $VERSION を削除しました"

  publish:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: 10
      # https://learn.microsoft.com/en-us/nuget/nuget-org/trusted-publishing
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
      - run: mkdir -p ./artifacts
      - run: |
          dotnet build -c Release
          dotnet pack -o ./artifacts
      - run: dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{steps.login.outputs.NUGET_API_KEY}} --skip-duplicate
      - run: gh release create ${{github.ref_name}} --generate-notes ./artifacts/*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
